/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacklogOrderingRouteImport } from './routes/backlog-ordering'
import { Route as ProductGoalRouteImport } from './routes/product-goal'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SplittingRouteImport } from './routes/splitting'
import { Route as StoryMappingRouteImport } from './routes/story-mapping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogOrderingRoute = BacklogOrderingRouteImport.update({
  id: '/backlog-ordering',
  path: '/backlog-ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductGoalRoute = ProductGoalRouteImport.update({
  id: '/product-goal',
  path: '/product-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SplittingRoute = SplittingRouteImport.update({
  id: '/splitting',
  path: '/splitting',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryMappingRoute = StoryMappingRouteImport.update({
  id: '/story-mapping',
  path: '/story-mapping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog-ordering'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/story-mapping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog-ordering'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/story-mapping'
  id:
    | '__root__'
    | '/'
    | '/backlog-ordering'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/story-mapping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogOrderingRoute: typeof BacklogOrderingRoute
  ProductGoalRoute: typeof ProductGoalRoute
  RoadmapRoute: typeof RoadmapRoute
  SplittingRoute: typeof SplittingRoute
  StoryMappingRoute: typeof StoryMappingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog-ordering': {
      id: '/backlog-ordering'
      path: '/backlog-ordering'
      fullPath: '/backlog-ordering'
      preLoaderRoute: typeof BacklogOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-goal': {
      id: '/product-goal'
      path: '/product-goal'
      fullPath: '/product-goal'
      preLoaderRoute: typeof ProductGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitting': {
      id: '/splitting'
      path: '/splitting'
      fullPath: '/splitting'
      preLoaderRoute: typeof SplittingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-mapping': {
      id: '/story-mapping'
      path: '/story-mapping'
      fullPath: '/story-mapping'
      preLoaderRoute: typeof StoryMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogOrderingRoute: BacklogOrderingRoute,
  ProductGoalRoute: ProductGoalRoute,
  RoadmapRoute: RoadmapRoute,
  SplittingRoute: SplittingRoute,
  StoryMappingRoute: StoryMappingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
