/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountabilitiesRouteImport } from './routes/accountabilities'
import { Route as BacklogOrderingRouteImport } from './routes/backlog-ordering'
import { Route as EbmRouteImport } from './routes/ebm'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as ProductGoalRouteImport } from './routes/product-goal'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SplittingRouteImport } from './routes/splitting'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as StoryMappingRouteImport } from './routes/story-mapping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountabilitiesRoute = AccountabilitiesRouteImport.update({
  id: '/accountabilities',
  path: '/accountabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogOrderingRoute = BacklogOrderingRouteImport.update({
  id: '/backlog-ordering',
  path: '/backlog-ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const EbmRoute = EbmRouteImport.update({
  id: '/ebm',
  path: '/ebm',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductGoalRoute = ProductGoalRouteImport.update({
  id: '/product-goal',
  path: '/product-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SplittingRoute = SplittingRouteImport.update({
  id: '/splitting',
  path: '/splitting',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryMappingRoute = StoryMappingRouteImport.update({
  id: '/story-mapping',
  path: '/story-mapping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountabilities': typeof AccountabilitiesRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/ebm': typeof EbmRoute
  '/forecasting': typeof ForecastingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountabilities': typeof AccountabilitiesRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/ebm': typeof EbmRoute
  '/forecasting': typeof ForecastingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountabilities': typeof AccountabilitiesRoute
  '/backlog-ordering': typeof BacklogOrderingRoute
  '/ebm': typeof EbmRoute
  '/forecasting': typeof ForecastingRoute
  '/product-goal': typeof ProductGoalRoute
  '/roadmap': typeof RoadmapRoute
  '/splitting': typeof SplittingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/story-mapping': typeof StoryMappingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountabilities'
    | '/backlog-ordering'
    | '/ebm'
    | '/forecasting'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/stakeholders'
    | '/story-mapping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountabilities'
    | '/backlog-ordering'
    | '/ebm'
    | '/forecasting'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/stakeholders'
    | '/story-mapping'
  id:
    | '__root__'
    | '/'
    | '/accountabilities'
    | '/backlog-ordering'
    | '/ebm'
    | '/forecasting'
    | '/product-goal'
    | '/roadmap'
    | '/splitting'
    | '/stakeholders'
    | '/story-mapping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountabilitiesRoute: typeof AccountabilitiesRoute
  BacklogOrderingRoute: typeof BacklogOrderingRoute
  EbmRoute: typeof EbmRoute
  ForecastingRoute: typeof ForecastingRoute
  ProductGoalRoute: typeof ProductGoalRoute
  RoadmapRoute: typeof RoadmapRoute
  SplittingRoute: typeof SplittingRoute
  StakeholdersRoute: typeof StakeholdersRoute
  StoryMappingRoute: typeof StoryMappingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountabilities': {
      id: '/accountabilities'
      path: '/accountabilities'
      fullPath: '/accountabilities'
      preLoaderRoute: typeof AccountabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog-ordering': {
      id: '/backlog-ordering'
      path: '/backlog-ordering'
      fullPath: '/backlog-ordering'
      preLoaderRoute: typeof BacklogOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebm': {
      id: '/ebm'
      path: '/ebm'
      fullPath: '/ebm'
      preLoaderRoute: typeof EbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-goal': {
      id: '/product-goal'
      path: '/product-goal'
      fullPath: '/product-goal'
      preLoaderRoute: typeof ProductGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitting': {
      id: '/splitting'
      path: '/splitting'
      fullPath: '/splitting'
      preLoaderRoute: typeof SplittingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-mapping': {
      id: '/story-mapping'
      path: '/story-mapping'
      fullPath: '/story-mapping'
      preLoaderRoute: typeof StoryMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountabilitiesRoute: AccountabilitiesRoute,
  BacklogOrderingRoute: BacklogOrderingRoute,
  EbmRoute: EbmRoute,
  ForecastingRoute: ForecastingRoute,
  ProductGoalRoute: ProductGoalRoute,
  RoadmapRoute: RoadmapRoute,
  SplittingRoute: SplittingRoute,
  StakeholdersRoute: StakeholdersRoute,
  StoryMappingRoute: StoryMappingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
